version: '2'
services:
    tests:
        build:
            context: .
        network_mode: "host"
        cap_add:
            - SYS_PTRACE
              #privileged: true
        ulimits:
            core:
                soft: -1
                hard: -1
